# Generated by Django 2.0.9 on 2018-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.TextField(max_length=8)),
                ('district', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('photo', models.ImageField(upload_to='companies')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.')),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Restaurants', 'Restaurants'), ('Hairdressers', 'Hairdressers'), ('Pharmacies', 'Pharmacies')], default='', max_length=200)),
                ('nr_searches', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
